### PR TITLE
Git week1

### PR DESCRIPTION
**Pull request by shobanamg**
updated as per review commends.

### CODE REVIEW

**Review by marta-ov — CHANGES_REQUESTED** [review]
This is great! :D
I have one last task for you, to mimic the process of implementing mentor feedback, can you please add another country name to the file countries.txt, add/commit/push please?
You'll see that the new commit will automatically show up in this PR :)

**Comment by marta-ov** [comment]
On exercise 1, i see that your .gitignore file is named `.gitignore,`, i.e. it has a comma at the end, which shouldn't be there. Can you fix that please?

**Comment by shobanamg** [comment]
updated as per review commends.

**Review by marta-ov — APPROVED** [review]
Great!  Please go ahead and merge the PR :)

**Comment by shobanamg** [comment]
> Great! Please go ahead and merge the PR :)

**Comment by shobanamg** [comment]
Sure, Thanks.

**Pull request merged**
